# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DataInterface(object):
    def setupUi(self, DataInterface):
        DataInterface.setObjectName("DataInterface")
        DataInterface.resize(993, 672)
        self.gridLayout = QtWidgets.QGridLayout(DataInterface)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(966, 37, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.TitleLabel = TitleLabel(DataInterface)
        self.TitleLabel.setProperty("pixelFontSize", 50)
        self.TitleLabel.setObjectName("TitleLabel")
        self.horizontalLayout.addWidget(self.TitleLabel)
        self.themeButton = ToolButton(DataInterface)
        self.themeButton.setObjectName("themeButton")
        self.horizontalLayout.addWidget(self.themeButton)
        self.GitHubButton = ToolButton(DataInterface)
        self.GitHubButton.setObjectName("GitHubButton")
        self.horizontalLayout.addWidget(self.GitHubButton)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(DataInterface)
        self.stackedWidget.setObjectName("stackedWidget")
        self.caloriesPage = QtWidgets.QWidget()
        self.caloriesPage.setObjectName("caloriesPage")
        self.caloriesGridLayout = QtWidgets.QGridLayout(self.caloriesPage)
        self.caloriesGridLayout.setObjectName("caloriesGridLayout")
        self.caloriesCardWidget = CardWidget(self.caloriesPage)
        self.caloriesCardWidget.setObjectName("caloriesCardWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.caloriesCardWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.caloriesGridLayout.addWidget(self.caloriesCardWidget, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.caloriesPage)
        self.floorPage = QtWidgets.QWidget()
        self.floorPage.setObjectName("floorPage")
        self.floorGridLayout = QtWidgets.QGridLayout(self.floorPage)
        self.floorGridLayout.setObjectName("floorGridLayout")
        self.floorCardWidget = CardWidget(self.floorPage)
        self.floorCardWidget.setObjectName("floorCardWidget")
        self.floorCardGridLayout = QtWidgets.QGridLayout(self.floorCardWidget)
        self.floorCardGridLayout.setObjectName("floorCardGridLayout")
        self.DisplayLabel_2 = DisplayLabel(self.floorCardWidget)
        self.DisplayLabel_2.setObjectName("DisplayLabel_2")
        self.floorCardGridLayout.addWidget(self.DisplayLabel_2, 0, 0, 1, 1)
        self.floorGridLayout.addWidget(self.floorCardWidget, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.floorPage)
        self.distancePage = QtWidgets.QWidget()
        self.distancePage.setObjectName("distancePage")
        self.distanceGridLayout = QtWidgets.QGridLayout(self.distancePage)
        self.distanceGridLayout.setObjectName("distanceGridLayout")
        self.distanceCardWidget = CardWidget(self.distancePage)
        self.distanceCardWidget.setObjectName("distanceCardWidget")
        self.distanceCardGridLayout = QtWidgets.QGridLayout(self.distanceCardWidget)
        self.distanceCardGridLayout.setObjectName("distanceCardGridLayout")
        self.DisplayLabel_3 = DisplayLabel(self.distanceCardWidget)
        self.DisplayLabel_3.setObjectName("DisplayLabel_3")
        self.distanceCardGridLayout.addWidget(self.DisplayLabel_3, 0, 0, 1, 1)
        self.distanceGridLayout.addWidget(self.distanceCardWidget, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.distancePage)
        self.stepPage = QtWidgets.QWidget()
        self.stepPage.setObjectName("stepPage")
        self.stepGridLayout = QtWidgets.QGridLayout(self.stepPage)
        self.stepGridLayout.setObjectName("stepGridLayout")
        self.stepCardWidget = CardWidget(self.stepPage)
        self.stepCardWidget.setObjectName("stepCardWidget")
        self.stepCardGridLayout = QtWidgets.QGridLayout(self.stepCardWidget)
        self.stepCardGridLayout.setObjectName("stepCardGridLayout")
        self.DisplayLabel_4 = DisplayLabel(self.stepCardWidget)
        self.DisplayLabel_4.setObjectName("DisplayLabel_4")
        self.stepCardGridLayout.addWidget(self.DisplayLabel_4, 0, 0, 1, 1)
        self.stepGridLayout.addWidget(self.stepCardWidget, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.stepPage)
        self.gridLayout.addWidget(self.stackedWidget, 3, 0, 1, 1)
        self.pivot = SegmentedWidget(DataInterface)
        self.pivot.setAutoFillBackground(False)
        self.pivot.setObjectName("pivot")
        self.gridLayout.addWidget(self.pivot, 2, 0, 1, 1)

        self.retranslateUi(DataInterface)
        QtCore.QMetaObject.connectSlotsByName(DataInterface)

    def retranslateUi(self, DataInterface):
        _translate = QtCore.QCoreApplication.translate
        DataInterface.setWindowTitle(_translate("DataInterface", "Form"))
        self.TitleLabel.setText(_translate("DataInterface", "My Data"))
        self.DisplayLabel_2.setText(_translate("DataInterface", "Floor Diagram"))
        self.DisplayLabel_3.setText(_translate("DataInterface", "Distance Diagram"))
        self.DisplayLabel_4.setText(_translate("DataInterface", "Step Diagram"))
from qfluentwidgets import CardWidget, DisplayLabel, SegmentedWidget, TitleLabel, ToolButton
