# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'group_stack_group_list_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GroupStackGroupListPage(object):
    def setupUi(self, GroupStackGroupListPage):
        GroupStackGroupListPage.setObjectName("GroupStackGroupListPage")
        GroupStackGroupListPage.resize(400, 300)
        self.textBrowser = QtWidgets.QTextBrowser(GroupStackGroupListPage)
        self.textBrowser.setGeometry(QtCore.QRect(0, 0, 256, 192))
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(GroupStackGroupListPage)
        QtCore.QMetaObject.connectSlotsByName(GroupStackGroupListPage)

    def retranslateUi(self, GroupStackGroupListPage):
        _translate = QtCore.QCoreApplication.translate
        GroupStackGroupListPage.setWindowTitle(_translate("GroupStackGroupListPage", "Form"))
        self.textBrowser.setHtml(_translate("GroupStackGroupListPage", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Group list</p></body></html>"))
