# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Study\University\Y2T1\OOP\Health-Tracker\health_tracker\health_app_pyqt\ui\group_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GroupInterface(object):
    def setupUi(self, GroupInterface):
        GroupInterface.setObjectName("GroupInterface")
        GroupInterface.resize(984, 671)
        self.verticalLayout = QtWidgets.QVBoxLayout(GroupInterface)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(966, 37, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.TitleLabel = TitleLabel(GroupInterface)
        self.TitleLabel.setProperty("pixelFontSize", 50)
        self.TitleLabel.setObjectName("TitleLabel")
        self.verticalLayout.addWidget(self.TitleLabel)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)

        self.retranslateUi(GroupInterface)
        QtCore.QMetaObject.connectSlotsByName(GroupInterface)

    def retranslateUi(self, GroupInterface):
        _translate = QtCore.QCoreApplication.translate
        GroupInterface.setWindowTitle(_translate("GroupInterface", "Form"))
        self.TitleLabel.setText(_translate("GroupInterface", "Group"))
from qfluentwidgets import TitleLabel
