# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'group_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GroupInterface(object):
    def setupUi(self, GroupInterface):
        GroupInterface.setObjectName("GroupInterface")
        GroupInterface.resize(984, 671)
        self.verticalLayout = QtWidgets.QVBoxLayout(GroupInterface)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(966, 37, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.TitleLabel = TitleLabel(GroupInterface)
        self.TitleLabel.setProperty("pixelFontSize", 50)
        self.TitleLabel.setObjectName("TitleLabel")
        self.horizontalLayout.addWidget(self.TitleLabel)
        self.groupThemeButton = ToolButton(GroupInterface)
        self.groupThemeButton.setObjectName("groupThemeButton")
        self.horizontalLayout.addWidget(self.groupThemeButton)
        self.GitHubButton = ToolButton(GroupInterface)
        self.GitHubButton.setObjectName("GitHubButton")
        self.horizontalLayout.addWidget(self.GitHubButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.stackedWidget = QtWidgets.QStackedWidget(GroupInterface)
        self.stackedWidget.setAutoFillBackground(False)
        self.stackedWidget.setObjectName("stackedWidget")
        self.defaultPage = QtWidgets.QWidget()
        self.defaultPage.setObjectName("defaultPage")
        self.gridLayout = QtWidgets.QGridLayout(self.defaultPage)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(self.defaultPage)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.defaultPage)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.defaultPage)
        self.groupListPage = QtWidgets.QWidget()
        self.groupListPage.setObjectName("groupListPage")
        self.stackedWidget.addWidget(self.groupListPage)
        self.verticalLayout.addWidget(self.stackedWidget)

        self.retranslateUi(GroupInterface)
        QtCore.QMetaObject.connectSlotsByName(GroupInterface)

    def retranslateUi(self, GroupInterface):
        _translate = QtCore.QCoreApplication.translate
        GroupInterface.setWindowTitle(_translate("GroupInterface", "Form"))
        self.TitleLabel.setText(_translate("GroupInterface", "Group"))
        self.pushButton.setText(_translate("GroupInterface", "Password to Join Group"))
        self.pushButton_2.setText(_translate("GroupInterface", "Create Group"))
from qfluentwidgets import TitleLabel, ToolButton
