# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Study\University\Y2T1\OOP\Health-Tracker\health_tracker\health_app_pyqt\ui\health_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HealthInterface(object):
    def setupUi(self, HealthInterface):
        HealthInterface.setObjectName("HealthInterface")
        HealthInterface.resize(1090, 859)
        self.gridLayout_3 = QtWidgets.QGridLayout(HealthInterface)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.SimpleCardWidget = SimpleCardWidget(HealthInterface)
        self.SimpleCardWidget.setObjectName("SimpleCardWidget")
        self.gridLayout.addWidget(self.SimpleCardWidget, 3, 1, 1, 1)
        self.CardWidget = CardWidget(HealthInterface)
        self.CardWidget.setObjectName("CardWidget")
        self.gridLayout.addWidget(self.CardWidget, 1, 1, 1, 1)
        self.HeaderCardWidget = HeaderCardWidget(HealthInterface)
        self.HeaderCardWidget.setObjectName("HeaderCardWidget")
        self.TitleLabel = TitleLabel(self.HeaderCardWidget)
        self.TitleLabel.setGeometry(QtCore.QRect(20, 10, 124, 38))
        self.TitleLabel.setObjectName("TitleLabel")
        self.gridLayout.addWidget(self.HeaderCardWidget, 1, 0, 1, 1)
        self.ElevatedCardWidget = ElevatedCardWidget(HealthInterface)
        self.ElevatedCardWidget.setObjectName("ElevatedCardWidget")
        self.gridLayout.addWidget(self.ElevatedCardWidget, 3, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem, 0, 0, 1, 1)

        self.retranslateUi(HealthInterface)
        QtCore.QMetaObject.connectSlotsByName(HealthInterface)

    def retranslateUi(self, HealthInterface):
        _translate = QtCore.QCoreApplication.translate
        HealthInterface.setWindowTitle(_translate("HealthInterface", "Form"))
        self.TitleLabel.setText(_translate("HealthInterface", "Title label"))
from qfluentwidgets import CardWidget, ElevatedCardWidget, HeaderCardWidget, SimpleCardWidget, TitleLabel
