# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Study\University\Y2T1\OOP\Health-Tracker\health_tracker\health_app_pyqt\ui\login_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginInterface(object):
    def setupUi(self, LoginInterface):
        LoginInterface.setObjectName("LoginInterface")
        LoginInterface.resize(406, 604)
        self.verticalLayout = QtWidgets.QVBoxLayout(LoginInterface)
        self.verticalLayout.setContentsMargins(30, 35, 30, 15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.LargeTitleLabel = LargeTitleLabel(LoginInterface)
        self.LargeTitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.LargeTitleLabel.setObjectName("LargeTitleLabel")
        self.verticalLayout.addWidget(self.LargeTitleLabel)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.BodyLabel = BodyLabel(LoginInterface)
        self.BodyLabel.setObjectName("BodyLabel")
        self.verticalLayout.addWidget(self.BodyLabel)
        self.nameEdit = LineEdit(LoginInterface)
        self.nameEdit.setText("")
        self.nameEdit.setFrame(True)
        self.nameEdit.setPlaceholderText("")
        self.nameEdit.setProperty("transparent", True)
        self.nameEdit.setObjectName("nameEdit")
        self.verticalLayout.addWidget(self.nameEdit)
        self.BodyLabel_2 = BodyLabel(LoginInterface)
        self.BodyLabel_2.setObjectName("BodyLabel_2")
        self.verticalLayout.addWidget(self.BodyLabel_2)
        self.heightEdit = LineEdit(LoginInterface)
        self.heightEdit.setObjectName("heightEdit")
        self.verticalLayout.addWidget(self.heightEdit)
        self.BodyLabel_3 = BodyLabel(LoginInterface)
        self.BodyLabel_3.setObjectName("BodyLabel_3")
        self.verticalLayout.addWidget(self.BodyLabel_3)
        self.weightEdit = LineEdit(LoginInterface)
        self.weightEdit.setObjectName("weightEdit")
        self.verticalLayout.addWidget(self.weightEdit)
        self.BodyLabel_5 = BodyLabel(LoginInterface)
        self.BodyLabel_5.setObjectName("BodyLabel_5")
        self.verticalLayout.addWidget(self.BodyLabel_5)
        self.genderComboBox = ComboBox(LoginInterface)
        self.genderComboBox.setText("")
        self.genderComboBox.setObjectName("genderComboBox")
        self.verticalLayout.addWidget(self.genderComboBox)
        self.BodyLabel_4 = BodyLabel(LoginInterface)
        self.BodyLabel_4.setObjectName("BodyLabel_4")
        self.verticalLayout.addWidget(self.BodyLabel_4)
        self.birthdayCalendarPicker = CalendarPicker(LoginInterface)
        self.birthdayCalendarPicker.setObjectName("birthdayCalendarPicker")
        self.verticalLayout.addWidget(self.birthdayCalendarPicker)
        spacerItem1 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.loginButton = PrimaryPushButton(LoginInterface)
        self.loginButton.setObjectName("loginButton")
        self.horizontalLayout.addWidget(self.loginButton)
        self.guestButton = PrimaryPushButton(LoginInterface)
        self.guestButton.setObjectName("guestButton")
        self.horizontalLayout.addWidget(self.guestButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(LoginInterface)
        QtCore.QMetaObject.connectSlotsByName(LoginInterface)

    def retranslateUi(self, LoginInterface):
        _translate = QtCore.QCoreApplication.translate
        LoginInterface.setWindowTitle(_translate("LoginInterface", "Form"))
        self.LargeTitleLabel.setText(_translate("LoginInterface", "Login"))
        self.BodyLabel.setText(_translate("LoginInterface", "Nickname"))
        self.BodyLabel_2.setText(_translate("LoginInterface", "Height"))
        self.BodyLabel_3.setText(_translate("LoginInterface", "Weight"))
        self.BodyLabel_5.setText(_translate("LoginInterface", "Gender"))
        self.BodyLabel_4.setText(_translate("LoginInterface", "Birthday"))
        self.loginButton.setText(_translate("LoginInterface", "Login"))
        self.guestButton.setText(_translate("LoginInterface", "Login as Guest"))
from qfluentwidgets import BodyLabel, CalendarPicker, ComboBox, LargeTitleLabel, LineEdit, PrimaryPushButton
